version: "3"

services:
#  frontend:
#    build: frontend
#    container_name: frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

  backend:
    build: backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/root/backend
    env_file:
      - container.env
    depends_on:
      - db

  sensors:
    build: sensors
    container_name: sensors
    volumes:
      - ./sensors:/root/sensors
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    env_file:
      - container.env
    depends_on:
      - db

  db:
    image: andresvidal/rpi3-mongodb3
    container_name: db
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ./container_data/configdb:/data/configdb
      - ./container_data/db:/data/db
    command: >
      bash -c "rm /data/db/mongod.lock && mongod"
