version: "3"

services:
  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always

  backend:
    build: backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/root/backend
    env_file:
      - container.env
    depends_on:
      - db
    restart: always

  sensors:
    build: sensors
    container_name: sensors
    volumes:
      - ./sensors:/root/sensors
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    env_file:
      - container.env
    privileged: true
    depends_on:
      - db
    restart: always

  db:
    image: andresvidal/rpi3-mongodb3
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./container_data/configdb:/data/configdb
      - ./container_data/db:/data/db
    command: >
      bash -c "rm /data/db/mongod.lock && mongod"
    restart: always
